require_relative '../../../node_modules/.bun/@capacitor+ios@7.4.5+12459b436ab1bc92/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/.bun/@capacitor+ios@7.4.5+12459b436ab1bc92/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/.bun/@capacitor+ios@7.4.5+12459b436ab1bc92/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../node_modules/.bun/@capacitor+app@7.1.2+12459b436ab1bc92/node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../../node_modules/.bun/@capacitor+browser@7.0.4+12459b436ab1bc92/node_modules/@capacitor/browser'
  pod 'CapacitorSplashScreen', :path => '../../../node_modules/.bun/@capacitor+splash-screen@7.0.4+12459b436ab1bc92/node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../../node_modules/.bun/@capacitor+status-bar@7.0.4+12459b436ab1bc92/node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
